// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgSell } from "./types/swap/sale/tx";
import { MsgCancel } from "./types/swap/sale/tx";
import { MsgBuy } from "./types/swap/sale/tx";
import { MsgBuyNFT } from "./types/swap/sale/tx";
import { MsgCancelNFT } from "./types/swap/sale/tx";
import { MsgSellNFT } from "./types/swap/sale/tx";


export { MsgSell, MsgCancel, MsgBuy, MsgBuyNFT, MsgCancelNFT, MsgSellNFT };

type sendMsgSellParams = {
  value: MsgSell,
  fee?: StdFee,
  memo?: string
};

type sendMsgCancelParams = {
  value: MsgCancel,
  fee?: StdFee,
  memo?: string
};

type sendMsgBuyParams = {
  value: MsgBuy,
  fee?: StdFee,
  memo?: string
};

type sendMsgBuyNFTParams = {
  value: MsgBuyNFT,
  fee?: StdFee,
  memo?: string
};

type sendMsgCancelNFTParams = {
  value: MsgCancelNFT,
  fee?: StdFee,
  memo?: string
};

type sendMsgSellNFTParams = {
  value: MsgSellNFT,
  fee?: StdFee,
  memo?: string
};


type msgSellParams = {
  value: MsgSell,
};

type msgCancelParams = {
  value: MsgCancel,
};

type msgBuyParams = {
  value: MsgBuy,
};

type msgBuyNFTParams = {
  value: MsgBuyNFT,
};

type msgCancelNFTParams = {
  value: MsgCancelNFT,
};

type msgSellNFTParams = {
  value: MsgSellNFT,
};


export const registry = new Registry(msgTypes);

const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgSell({ value, fee, memo }: sendMsgSellParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgSell: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgSell({ value: MsgSell.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgSell: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgCancel({ value, fee, memo }: sendMsgCancelParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCancel: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgCancel({ value: MsgCancel.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCancel: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgBuy({ value, fee, memo }: sendMsgBuyParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgBuy: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgBuy({ value: MsgBuy.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgBuy: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgBuyNFT({ value, fee, memo }: sendMsgBuyNFTParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgBuyNFT: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgBuyNFT({ value: MsgBuyNFT.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgBuyNFT: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgCancelNFT({ value, fee, memo }: sendMsgCancelNFTParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCancelNFT: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgCancelNFT({ value: MsgCancelNFT.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCancelNFT: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgSellNFT({ value, fee, memo }: sendMsgSellNFTParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgSellNFT: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgSellNFT({ value: MsgSellNFT.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgSellNFT: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgSell({ value }: msgSellParams): EncodeObject {
			try {
				return { typeUrl: "/swap.sale.MsgSell", value: MsgSell.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgSell: Could not create message: ' + e.message)
			}
		},
		
		msgCancel({ value }: msgCancelParams): EncodeObject {
			try {
				return { typeUrl: "/swap.sale.MsgCancel", value: MsgCancel.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCancel: Could not create message: ' + e.message)
			}
		},
		
		msgBuy({ value }: msgBuyParams): EncodeObject {
			try {
				return { typeUrl: "/swap.sale.MsgBuy", value: MsgBuy.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgBuy: Could not create message: ' + e.message)
			}
		},
		
		msgBuyNFT({ value }: msgBuyNFTParams): EncodeObject {
			try {
				return { typeUrl: "/swap.sale.MsgBuyNFT", value: MsgBuyNFT.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgBuyNFT: Could not create message: ' + e.message)
			}
		},
		
		msgCancelNFT({ value }: msgCancelNFTParams): EncodeObject {
			try {
				return { typeUrl: "/swap.sale.MsgCancelNFT", value: MsgCancelNFT.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCancelNFT: Could not create message: ' + e.message)
			}
		},
		
		msgSellNFT({ value }: msgSellNFTParams): EncodeObject {
			try {
				return { typeUrl: "/swap.sale.MsgSellNFT", value: MsgSellNFT.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgSellNFT: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			SwapSale: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;